title: P5 Guide theme
author: Mio Bambino
description: Custom template for a persona 5 website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://miosblog.de" # the base hostname & protocol for your site, e.g. http://example.com
lang: en
timezone: UTC
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - jekyll-p5-guide.gemspec

# ganalytics
google_analytics:

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

# Outputting
permalink: /:year:month:day:title/

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
